"""empty message

Revision ID: 5632adc2bb6f
Revises: 5ef7b184e95e
Create Date: 2023-02-13 11:11:01.381332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5632adc2bb6f'
down_revision = '5ef7b184e95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=950), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('url1', sa.String(length=250), nullable=True),
    sa.Column('url2', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('user_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('admin')
        batch_op.drop_column('premium')
        batch_op.drop_column('user_url')
        batch_op.drop_column('username')

    op.drop_table('services')
    # ### end Alembic commands ###
